version: '3.7'

services:
  db:
    image: postgres:10.16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - rainforest/.env
    expose:
      - 5432

  web:
    build: ./rainforest
    command: >
      sh -c "python /app/manage.py migrate
      && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./rainforest:/app
    ports:
      - "8000:8000"
    env_file:
      - rainforest/.env
    depends_on:
      - db

  celery:
    build: ./rainforest
    command: celery -A rainforest worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./rainforest:/app
    env_file:
      - rainforest/.env
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine
volumes:
  postgres_data: