version: '3.7'

services:
  db:
    image: postgres:10.16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - rainforest/.env
    expose:
      - 5432

  web:
    build:
      context: 'rainforest/'
    command: >
      sh -c "python /app/rainforest/manage.py migrate
      && python /app/rainforest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - rainforest/.env
    depends_on:
      - db
volumes:
  postgres_data: