# Generated by Django 3.2.8 on 2021-10-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='when order is created')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='sum prices of products in order')),
                ('status', models.IntegerField(choices=[(1, 'PAID'), (2, 'UNPAID'), (3, 'CANCELED'), (4, 'RETURNED')], default=2, verbose_name='status order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title of product')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='self cost of product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price of product')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity of product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('total_cost_by_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='sum self cost of one type of products in order')),
                ('total_price_by_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='sum price of one type of products in order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='store.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='store.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='store.ProductsInOrder', to='store.Product', verbose_name='products in order'),
        ),
    ]
