# Generated by Django 3.2.8 on 2021-10-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
