# Generated by Django 3.2.8 on 2021-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productsinorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='total_price_by_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
    ]
