# Generated by Django 3.2.8 on 2021-10-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211016_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='total_cost_by_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='store.ProductsInOrder', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='store.order'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='store.product'),
        ),
    ]
