# Generated by Django 3.2.8 on 2021-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
