# Generated by Django 3.2.8 on 2021-10-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_reports_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
